<!DOCTYPE html>
<html>

  <head>
    <title>Lead Concentration Analysis</title>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Pontano+Sans&display=swap" rel="stylesheet">
    <link href="https://opensource.keycdn.com/fontawesome/4.6.3/font-awesome.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <style>
	.parallax {
	  /* The image used */
	  background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('images/leadpipe-background.jpg');

	  /* Set a specific height */
	  min-height: 100px; 

	  /* Create the parallax scrolling effect */
	  background-attachment: fixed;
	  background-position: center;
	  background-repeat: no-repeat;
	  background-size: cover;
	}
	</style>
  </head>

  <body style="margin-bottom: 50px"> 
  	<div class="parallax">
		<div id="inputform"> 
			<h3>Find the lead concentration in public schools in your area</h3>
			<form action="lead_analysis.php" method="post">
				<strong>ZIP Code: </strong><input class="zip_code" type="text" name="zip_code"><br>
				<strong><input class="submit-btn" type="submit" name="submit-btn"></strong>
			</form> 
		</div>
  	</div>

  	<div id="description">
  		<h1>Lead Concentration Analysis</h1>
  		<h3>Ever since the outcry over Flint, Michigan's heightened lead concentration in public water systems, which were used by facilities including schools, there has been a greater demand for quality water. To analyze how lead poisoning could potentially impact schoolchildren across the United States, we visualize lead concentration in schools in the populous state of New York.</h3>
  	</div>

  	<div id="misc-info">
  		<h2>Results generated by</h2>
  		<img src="images/logo.jpg">
  	</div>

  </body>

</html>